Repository LCOGT/neoexchange, pull requests merged in 2021-11, with the labels that each got.

#572 Feature/dithering
  neoexchange/astrometrics/sources_subs.py
  neoexchange/astrometrics/tests/test_sources_subs.py
  neoexchange/core/forms.py
  neoexchange/core/templates/core/schedule_confirm.html
  neoexchange/core/tests/test_views.py
  neoexchange/core/views.py
  neoexchange/neox/tests/test_schedule_observations.py
Labels: enhancement, comets

#574 Issue 573
  neoexchange/core/tests/test_views.py
  neoexchange/core/views.py
  neoexchange/neox/tests/test_data_summarypage.py
Labels: bug

#558 Feature/damit
  Dockerfile
  README.md
  neoexchange/astrometrics/ephem_subs.py
  neoexchange/astrometrics/tests/test_ephem_subs.py
  neoexchange/core/management/commands/download_process_data.py
  neoexchange/core/management/commands/lc_analysis.py
  neoexchange/core/management/commands/lightcurve_extraction.py
  neoexchange/core/models/dataproducts.py
  neoexchange/core/plots.py
  neoexchange/core/static/core/js/bokeh_custom_javascript.js
  neoexchange/core/templates/core/plot_lc.html
  neoexchange/core/tests/test_views.py
  neoexchange/core/utils.py
  neoexchange/core/views.py
  neoexchange/neox/settings.py
  neoexchange/neox/tests/test_plot_lc.py
  neoexchange/neox/urls.py
  neoexchange/photometrics/catalog_subs.py
  neoexchange/photometrics/external_codes.py
  neoexchange/photometrics/gf_movie.py
Labels: enhancement

#576 fix lc plots to handle comets
  README.md
  neoexchange/astrometrics/ephem_subs.py
  neoexchange/core/plots.py
  neoexchange/neox/settings.py
  neoexchange/neox/tests/test_plot_lc.py
Labels: bug, comets

#579 Fix Issue 578
  neoexchange/core/models/frame.py
  neoexchange/core/models/sources.py
  neoexchange/core/tests/test_models.py
  neoexchange/core/tests/test_mpc_submit.py
  neoexchange/core/tests/test_views.py
  neoexchange/neox/tests/test_measurements.py
  neoexchange/photometrics/tests/test_spectraplot.py
Labels: bug
