Repository LCOGT/neoexchange, pull requests merged in 2021-07, with the labels that each got.

#556 Fix movie maker when target is far outside range.
  neoexchange/photometrics/gf_movie.py
Labels: bug, intermittent

#561 Adds support for TFN telescopes (Issue #555)
  README.md
  neoexchange/astrometrics/ephem_subs.py
  neoexchange/astrometrics/site_config.py
  neoexchange/astrometrics/sources_subs.py
  neoexchange/astrometrics/tests/test_ephem_subs.py
  neoexchange/astrometrics/tests/test_sources_subs.py
  neoexchange/core/forms.py
  neoexchange/core/tests/test_forms.py
  neoexchange/neox/settings.py
  neoexchange/neox/tests/test_ephemeris_creation.py
Labels: enhancement

#562 Bugfix TFN issues
  neoexchange/astrometrics/sources_subs.py
  neoexchange/astrometrics/tests/test_sources_subs.py
  neoexchange/core/models/blocks.py
  neoexchange/core/models/frame.py
  neoexchange/core/tests/test_models.py
Labels: bug
